### ISSUE TITLE
crate-private trait `FloatLike` in public interface (v0.2.0)

### ISSUE THREAD

**Issue by LDeakin** [mwlon/pcodec#177]
Me again! The 0.2.0 release introduces a bug:

```
error[E0445]: crate-private trait `FloatLike` in public interface
  --> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pco-0.2.0/src/float_mult_utils.rs:9:1
   |
9  |   pub fn join_latents<F: FloatLike>(base: F, primary: &mut [F::L], secondary: &[F::L]) {
   |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't leak crate-private trait
   |
  ::: /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pco-0.2.0/src/data_types/mod.rs:20:1
   |
20 | / pub(crate) trait FloatLike:
21 | |   Add<Output = Self>
22 | |   + AddAssign
23 | |   + Copy
...  |
33 | |   + SubAssign
34 | |   + Div<Output = Self>
   | |______________________- `FloatLike` declared as crate-private
```

Relevant CI run triggering this issue:
https://github.com/LDeakin/zarrs/actions/runs/8367021385/job/22908525341?pr=15

**Comment by mwlon** [comment]
I think this is actually a bug in older versions of cargo - the `join_latents` function is crate-private. Are you able to rustup to a newer version?

**Comment by mwlon** [comment]
Yeah, looks like the minimum Rust version should really be 1.74. I suppose it wasn't a bug per se, but a change in the language: https://rust-lang.github.io/rfcs/2145-type-privacy.html

**Comment by mwlon** [comment]
Well that's annoying, but I just published another version (0.2.1) that should work in 1.73.
